<%@taglib uri="http://www.springframework.org/tags" prefix="spring"%>
<%@taglib uri="http://www.springframework.org/tags/form" prefix="form"%>
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib prefix="s" uri="/struts-tags"%>
<%@ page contentType="text/html;charset=UTF-8"%>
<!DOCTYPE HTML>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"> 
<meta name="format-detection" content="telephone=no" />
<meta name="viewport" content="width=device-width initial-scale=1.0 maximum-scale=1.0 user-scalable=yes" />
<title>江西卫生职业学院-工资查询</title>
<link href="<c:url value='/resources/chaxun/css/wage.css' />" rel="stylesheet" type="text/css">
</head>

<body>
<div class="nav">
    <div class="menu">
        <div class="top1"><a href="index.html"></a></div>
        <div class="top2"><h1>工资查询</h1></div>
        <div class="top3"></div>
    </div>
</div>
<div class="global">
    <div class="selBox">
        <div class="sel">
        <select>
            <option selected>请选择年份</option>
            <option>2017</option>
            <option>2016</option>
            <option>2015</option>
        </select>
        </div>
    </div>
    <div class="tabBox">
        <table border="0" cellspacing="0" cellpadding="0" class="tabsData">
            <tr>
                <th>人员代码</th>
                <th>姓名</th>
                <th>年</th>
                <th>月</th>
                <th>岗位工资</th>
                <th>薪级工资</th>
                <th>职务十(中系)</th>
                <th>教护龄</th>
                <th>基本工资合计</th>
                <th>职务工资</th>
                <th>保留津贴</th>
                <th>职务10(其他)</th>
                <th>菜蓝子</th>
                <th>物价补贴</th>
                <th>卫生贴</th>
                <th>通讯费</th>
                <th>月奖</th>
                <th>特贴</th>
                <th>基础性绩效合计</th>
                <th>考勤</th>
                <th>其它收入</th>
                <th>班主任津贴</th>
                <th>实习班主任</th>
                <th>成教班主任津贴、监考</th>
                <th>课时费</th>
                <th>监考费</th>
                <th>军训补助</th>
                <th>运动会补贴</th>
                <th>值班费</th>
                <th>成教课时费</th>
                <th>误餐补贴</th>
                <th>中餐</th>
                <th>教研室负责人补贴</th>
                <th>奖励性绩效合计</th>
                <th>精神文明奖</th>
                <th>综治奖</th>
                <th>节能奖</th>
                <th>降温、取暖费</th>
                <th>住房补贴</th>
                <th>科研奖</th>
                <th>政府奖励合计</th>
                <th>失业金</th>
                <th>失业险固定</th>
                <th>公积金</th>
                <th>工会费</th>
                <th>保险</th>
                <th>税款</th>
                <th>电费</th>
                <th>水费</th>
                <th>医药费</th>
                <th>规范津补贴减少额</th>
                <th>养老保险预缴</th>
                <th>扣款</th>
                <th>病事假扣款</th>
                <th>职业年金</th>
                <th>扣款合计</th>
                <th>停发工资</th>
                <th>公积金差额</th>
                <th>应税工资</th>
                <th>计税工资</th>
                <th>实发工资</th>
                <th>备注</th>
                <th>是否失保计算</th>
            </tr>
            <tr>
                <td>2106041</td>
                <td>文旭</td>
                <td>2017</td>
                <td>5</td>
                <td>1950</td>
                <td>1331</td>
                <td>0</td>
                <td>5</td>
                <td>3286</td>
                <td>270</td>
                <td>48</td>
                <td>329</td>
                <td>200</td>
                <td>30</td>
                <td>0</td>
                <td>220</td>
                <td>2300</td>
                <td>0</td>
                <td>3397</td>
                <td>214</td>
                <td>0</td>
                <td>287</td>
                <td>0</td>
                <td>0</td>
                <td>800</td>
                <td>0</td>
                <td>0</td>
                <td>0</td>
                <td>0</td>
                <td>0</td>
                <td>0</td>
                <td>0</td>
                <td>0</td>
                <td>1301</td>
                <td>0</td>
                <td>0</td>
                <td>0</td>
                <td>0</td>
                <td>0</td>
                <td>0</td>
                <td>0</td>
                <td>39.63</td>
                <td>0</td>
                <td>1243.56</td>
                <td>16.41</td>
                <td>0</td>
                <td>87.19</td>
                <td>0</td>
                <td>0</td>
                <td>153.48</td>
                <td>0</td>
                <td>739.36</td>
                <td>0</td>
                <td>0</td>
                <td>369.68</td>
                <td>2649.31</td>
                <td>0</td>
                <td>0</td>
                <td>0</td>
                <td>5421.88</td>
                <td>5334.69</td>
                <td>备注</td>
                <td>1</td>
            </tr>
            <tr>
                <td>2106041</td>
                <td>文旭</td>
                <td>2017</td>
                <td>5</td>
                <td>1950</td>
                <td>1331</td>
                <td>0</td>
                <td>5</td>
                <td>3286</td>
                <td>270</td>
                <td>48</td>
                <td>329</td>
                <td>200</td>
                <td>30</td>
                <td>0</td>
                <td>220</td>
                <td>2300</td>
                <td>0</td>
                <td>3397</td>
                <td>214</td>
                <td>0</td>
                <td>287</td>
                <td>0</td>
                <td>0</td>
                <td>800</td>
                <td>0</td>
                <td>0</td>
                <td>0</td>
                <td>0</td>
                <td>0</td>
                <td>0</td>
                <td>0</td>
                <td>0</td>
                <td>1301</td>
                <td>0</td>
                <td>0</td>
                <td>0</td>
                <td>0</td>
                <td>0</td>
                <td>0</td>
                <td>0</td>
                <td>39.63</td>
                <td>0</td>
                <td>1243.56</td>
                <td>16.41</td>
                <td>0</td>
                <td>87.19</td>
                <td>0</td>
                <td>0</td>
                <td>153.48</td>
                <td>0</td>
                <td>739.36</td>
                <td>0</td>
                <td>0</td>
                <td>369.68</td>
                <td>2649.31</td>
                <td>0</td>
                <td>0</td>
                <td>0</td>
                <td>5421.88</td>
                <td>5334.69</td>
                <td>备注</td>
                <td>1</td>
            </tr>
            <tr>
                <td>2106041</td>
                <td>文旭</td>
                <td>2017</td>
                <td>5</td>
                <td>1950</td>
                <td>1331</td>
                <td>0</td>
                <td>5</td>
                <td>3286</td>
                <td>270</td>
                <td>48</td>
                <td>329</td>
                <td>200</td>
                <td>30</td>
                <td>0</td>
                <td>220</td>
                <td>2300</td>
                <td>0</td>
                <td>3397</td>
                <td>214</td>
                <td>0</td>
                <td>287</td>
                <td>0</td>
                <td>0</td>
                <td>800</td>
                <td>0</td>
                <td>0</td>
                <td>0</td>
                <td>0</td>
                <td>0</td>
                <td>0</td>
                <td>0</td>
                <td>0</td>
                <td>1301</td>
                <td>0</td>
                <td>0</td>
                <td>0</td>
                <td>0</td>
                <td>0</td>
                <td>0</td>
                <td>0</td>
                <td>39.63</td>
                <td>0</td>
                <td>1243.56</td>
                <td>16.41</td>
                <td>0</td>
                <td>87.19</td>
                <td>0</td>
                <td>0</td>
                <td>153.48</td>
                <td>0</td>
                <td>739.36</td>
                <td>0</td>
                <td>0</td>
                <td>369.68</td>
                <td>2649.31</td>
                <td>0</td>
                <td>0</td>
                <td>0</td>
                <td>5421.88</td>
                <td>5334.69</td>
                <td>备注</td>
                <td>1</td>
            </tr>
            <tr>
                <td>2106041</td>
                <td>文旭</td>
                <td>2017</td>
                <td>5</td>
                <td>1950</td>
                <td>1331</td>
                <td>0</td>
                <td>5</td>
                <td>3286</td>
                <td>270</td>
                <td>48</td>
                <td>329</td>
                <td>200</td>
                <td>30</td>
                <td>0</td>
                <td>220</td>
                <td>2300</td>
                <td>0</td>
                <td>3397</td>
                <td>214</td>
                <td>0</td>
                <td>287</td>
                <td>0</td>
                <td>0</td>
                <td>800</td>
                <td>0</td>
                <td>0</td>
                <td>0</td>
                <td>0</td>
                <td>0</td>
                <td>0</td>
                <td>0</td>
                <td>0</td>
                <td>1301</td>
                <td>0</td>
                <td>0</td>
                <td>0</td>
                <td>0</td>
                <td>0</td>
                <td>0</td>
                <td>0</td>
                <td>39.63</td>
                <td>0</td>
                <td>1243.56</td>
                <td>16.41</td>
                <td>0</td>
                <td>87.19</td>
                <td>0</td>
                <td>0</td>
                <td>153.48</td>
                <td>0</td>
                <td>739.36</td>
                <td>0</td>
                <td>0</td>
                <td>369.68</td>
                <td>2649.31</td>
                <td>0</td>
                <td>0</td>
                <td>0</td>
                <td>5421.88</td>
                <td>5334.69</td>
                <td>备注</td>
                <td>1</td>
            </tr>
            <tr>
                <td>2106041</td>
                <td>文旭</td>
                <td>2017</td>
                <td>5</td>
                <td>1950</td>
                <td>1331</td>
                <td>0</td>
                <td>5</td>
                <td>3286</td>
                <td>270</td>
                <td>48</td>
                <td>329</td>
                <td>200</td>
                <td>30</td>
                <td>0</td>
                <td>220</td>
                <td>2300</td>
                <td>0</td>
                <td>3397</td>
                <td>214</td>
                <td>0</td>
                <td>287</td>
                <td>0</td>
                <td>0</td>
                <td>800</td>
                <td>0</td>
                <td>0</td>
                <td>0</td>
                <td>0</td>
                <td>0</td>
                <td>0</td>
                <td>0</td>
                <td>0</td>
                <td>1301</td>
                <td>0</td>
                <td>0</td>
                <td>0</td>
                <td>0</td>
                <td>0</td>
                <td>0</td>
                <td>0</td>
                <td>39.63</td>
                <td>0</td>
                <td>1243.56</td>
                <td>16.41</td>
                <td>0</td>
                <td>87.19</td>
                <td>0</td>
                <td>0</td>
                <td>153.48</td>
                <td>0</td>
                <td>739.36</td>
                <td>0</td>
                <td>0</td>
                <td>369.68</td>
                <td>2649.31</td>
                <td>0</td>
                <td>0</td>
                <td>0</td>
                <td>5421.88</td>
                <td>5334.69</td>
                <td>备注</td>
                <td>1</td>
            </tr>
            <tr>
                <td>2106041</td>
                <td>文旭</td>
                <td>2017</td>
                <td>5</td>
                <td>1950</td>
                <td>1331</td>
                <td>0</td>
                <td>5</td>
                <td>3286</td>
                <td>270</td>
                <td>48</td>
                <td>329</td>
                <td>200</td>
                <td>30</td>
                <td>0</td>
                <td>220</td>
                <td>2300</td>
                <td>0</td>
                <td>3397</td>
                <td>214</td>
                <td>0</td>
                <td>287</td>
                <td>0</td>
                <td>0</td>
                <td>800</td>
                <td>0</td>
                <td>0</td>
                <td>0</td>
                <td>0</td>
                <td>0</td>
                <td>0</td>
                <td>0</td>
                <td>0</td>
                <td>1301</td>
                <td>0</td>
                <td>0</td>
                <td>0</td>
                <td>0</td>
                <td>0</td>
                <td>0</td>
                <td>0</td>
                <td>39.63</td>
                <td>0</td>
                <td>1243.56</td>
                <td>16.41</td>
                <td>0</td>
                <td>87.19</td>
                <td>0</td>
                <td>0</td>
                <td>153.48</td>
                <td>0</td>
                <td>739.36</td>
                <td>0</td>
                <td>0</td>
                <td>369.68</td>
                <td>2649.31</td>
                <td>0</td>
                <td>0</td>
                <td>0</td>
                <td>5421.88</td>
                <td>5334.69</td>
                <td>备注</td>
                <td>1</td>
            </tr>
        </table>
    </div>
</div>
</body>
</html>
